import type { Review } from "@/types/content";

export const REVIEWS: readonly Review[] = [
  {
    id: "camila-rosa-gomes",
    author: "Camila Rosa Gomes",
    relativeDate: "6 meses atrás",
    rating: 5,
    quote: "“Alfredo é muito cuidadoso e comprometido, o produto que é utilizado é muito cheiroso”",
    sourceUrl: "https://www.google.com/maps/contrib/113089659287269548207/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-1.png",
  },
  {
    id: "bia-marina",
    author: "Bia Marina",
    relativeDate: "6 meses atrás",
    rating: 5,
    quote: "“Excelente serviço! Limpeza de qualidade, bom atendimento e trabalho muito limpo”",
    sourceUrl: "https://www.google.com/maps/contrib/107311281463588243509/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-2.png",
  },
  {
    id: "ketti-pars",
    author: "Ketti Pars",
    relativeDate: "11 meses atrás",
    rating: 5,
    quote: "“Super recomendo o trabalho do Fritz! Caprichoso, cuidadoso e empenhado em solucionar o problema.”",
    sourceUrl: "https://www.google.com/maps/contrib/109811868611662659037/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-3.png",
  },
  {
    id: "aline-grasso",
    author: "Aline Grasso",
    relativeDate: "um mês atrás",
    rating: 5,
    quote: "“Serviço impecável e ele deixa tudo bem limpinho depois. Passa pano no chão e tudo!”",
    sourceUrl: "https://www.google.com/maps/contrib/108130488889070730570/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-4.png",
  },
  {
    id: "fernanda-almeida",
    author: "Fernanda Almeida",
    relativeDate: "4 meses atrás",
    rating: 5,
    quote: "“Excelente serviço, atendimento e custo benefício! Deixou meu sofá e cadeiras impecaveis”",
    sourceUrl: "https://www.google.com/maps/contrib/111042481565476517886/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-5.png",
  },
  {
    id: "thays-leal",
    author: "Thays Leal",
    relativeDate: "5 meses atrás",
    rating: 5,
    quote: "“Serviço excelente! Impermeabilizei minhas cadeiras e cabeceira, ele isolou a parte de madeira com cuidado.”",
    sourceUrl: "https://www.google.com/maps/contrib/105085449511163122408/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-6.png",
  },
  {
    id: "andrey-eduardo",
    author: "Andrey Eduardo",
    relativeDate: "4 meses atrás",
    rating: 5,
    quote: "“os sofás ficaram perfeitos, bem limpos e parecendo novos. A impermeabilização também foi realizada com maestria”",
    sourceUrl: "https://www.google.com/maps/contrib/106761727875842005597/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-7.png",
  },
  {
    id: "vera-r",
    author: "Vera R",
    relativeDate: "3 meses atrás",
    rating: 5,
    quote: "“Foi muito boa,empresa top sempre faço com eles indico de olhos fechados 🥰🤩”",
    sourceUrl: "https://www.google.com/maps/contrib/114502203980078275041/reviews?hl=pt-BR",
    image: "/assets/images/avaliacoes/cliente-8.png",
  },
] as const;
